In [1]:
#comments and use of other attributes in data 
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer
from collections import Counter

In [2]:
import sklearnex
sklearnex.patch_sklearn()

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [3]:
data=pd.read_csv("train.csv",delimiter=",")
data.head()

tweet_id airline_sentiment    airline airline_sentiment_gold  \
0  567900433542488064          negative  Southwest                    NaN   
1  569989168903819264          positive  Southwest                    NaN   
2  568089179520954368          positive     United                    NaN   
3  568928195581513728          negative  Southwest                    NaN   
4  568594180014014464          negative     United                    NaN   

            name negativereason_gold  retweet_count  \
0  ColeyGirouard                 NaN              0   
1  WalterFaddoul                 NaN              0   
2      LocalKyle                 NaN              0   
3    amccarthy19                 NaN              0   
4        J_Okayy                 NaN              0   

                                                text tweet_coord  \
0  @SouthwestAir I am scheduled for the morning, ...         NaN   
1  @SouthwestAir seeing your workers time in and ...         NaN   
2  @united Flew ORD to Miami and back and  had gr...         NaN   
3     @SouthwestAir @dultch97 that's horse radish 😤🐴         NaN   
4  @united so our flight into ORD was delayed bec...         NaN   

               tweet_created              tweet_location  \
0  2015-02-17 20:16:29 -0800             Washington D.C.   
1  2015-02-23 14:36:22 -0800  Indianapolis, Indiana; USA   
2  2015-02-18 08:46:29 -0800                    Illinois   
3  2015-02-20 16:20:26 -0800                         NaN   
4  2015-02-19 18:13:11 -0800                         NaN   

                user_timezone  
0      Atlantic Time (Canada)  
1  Central Time (US & Canada)  
2  Central Time (US & Canada)  
3      Atlantic Time (Canada)  
4  Eastern Time (US & Canada)

In [4]:
data

tweet_id airline_sentiment     airline  \
0      567900433542488064          negative   Southwest   
1      569989168903819264          positive   Southwest   
2      568089179520954368          positive      United   
3      568928195581513728          negative   Southwest   
4      568594180014014464          negative      United   
...                   ...               ...         ...   
10975  569934458364813313           neutral    American   
10976  568564006329434113          positive      United   
10977  569643648910028801          negative  US Airways   
10978  568864981917110272          negative  US Airways   
10979  568929299350179840          negative      United   

      airline_sentiment_gold           name negativereason_gold  \
0                        NaN  ColeyGirouard                 NaN   
1                        NaN  WalterFaddoul                 NaN   
2                        NaN      LocalKyle                 NaN   
3                        NaN    amccarthy19                 NaN   
4                        NaN        J_Okayy                 NaN   
...                      ...            ...                 ...   
10975                    NaN  Cottopanama85                 NaN   
10976                    NaN   PaulBEsteves                 NaN   
10977                    NaN    runfixsteve                 NaN   
10978                    NaN     CLChicosky                 NaN   
10979                    NaN     JW_Blocker                 NaN   

       retweet_count                                               text  \
0                  0  @SouthwestAir I am scheduled for the morning, ...   
1                  0  @SouthwestAir seeing your workers time in and ...   
2                  0  @united Flew ORD to Miami and back and  had gr...   
3                  0     @SouthwestAir @dultch97 that's horse radish 😤🐴   
4                  0  @united so our flight into ORD was delayed bec...   
...              ...                                                ...   
10975              0                            @AmericanAir followback   
10976              0  @united thanks for the help. Wish the phone re...   
10977              0  @usairways the. Worst. Ever. #dca #customerser...   
10978              0  @nrhodes85: look! Another apology. DO NOT FLY ...   
10979              1  @united you are by far the worst airline. 4 pl...   

      tweet_coord              tweet_created              tweet_location  \
0             NaN  2015-02-17 20:16:29 -0800             Washington D.C.   
1             NaN  2015-02-23 14:36:22 -0800  Indianapolis, Indiana; USA   
2             NaN  2015-02-18 08:46:29 -0800                    Illinois   
3             NaN  2015-02-20 16:20:26 -0800                         NaN   
4             NaN  2015-02-19 18:13:11 -0800                         NaN   
...           ...                        ...                         ...   
10975         NaN  2015-02-23 10:58:58 -0800                 ohio,panama   
10976         NaN  2015-02-19 16:13:17 -0800                    Brooklyn   
10977         NaN  2015-02-22 15:43:24 -0800      St. Augustine, Florida   
10978         NaN  2015-02-20 12:09:15 -0800                         NaN   
10979         NaN  2015-02-20 16:24:49 -0800                         NaN   

                    user_timezone  
0          Atlantic Time (Canada)  
1      Central Time (US & Canada)  
2      Central Time (US & Canada)  
3          Atlantic Time (Canada)  
4      Eastern Time (US & Canada)  
...                           ...  
10975                         NaN  
10976  Eastern Time (US & Canada)  
10977                         NaN  
10978                         NaN  
10979                         NaN  

[10980 rows x 12 columns]

In [5]:
x=data
del x["tweet_id"]

In [6]:
y=data["airline_sentiment"]

In [7]:
y.describe()

count        10980
unique           3
top       negative
freq          6851
Name: airline_sentiment, dtype: object

In [8]:
x.describe()

retweet_count
count   10980.000000
mean        0.080965
std         0.740303
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        44.000000

In [9]:
print(data.describe())

       retweet_count
count   10980.000000
mean        0.080965
std         0.740303
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        44.000000


In [10]:
for att in data:
    x=len(set(data[att].values))
    print("------------",att," : ",x)
    if(x<20):
        print(set(data[att].values))

------------ airline_sentiment  :  3
{'neutral', 'positive', 'negative'}
------------ airline  :  6
{'United', 'American', 'US Airways', 'Virgin America', 'Southwest', 'Delta'}
------------ airline_sentiment_gold  :  4
{nan, 'neutral', 'positive', 'negative'}
------------ name  :  6438
------------ negativereason_gold  :  12
{nan, 'Lost Luggage\nDamaged Luggage', 'Cancelled Flight\nCustomer Service Issue', 'Cancelled Flight', 'Late Flight\nCancelled Flight', "Customer Service Issue\nCan't Tell", 'Late Flight\nFlight Attendant Complaints', 'Bad Flight', "Can't Tell", 'Customer Service Issue', 'Late Flight', 'Customer Service Issue\nLost Luggage'}
------------ retweet_count  :  15
{0, 1, 2, 3, 4, 5, 6, 7, 8, 44, 15, 18, 22, 28, 31}
------------ text  :  10851
------------ tweet_coord  :  633
------------ tweet_created  :  10758
------------ tweet_location  :  2659
------------ user_timezone  :  79


In [11]:
len(data)-data.isnull().sum()

airline_sentiment         10980
airline                   10980
airline_sentiment_gold       31
name                      10980
negativereason_gold          24
retweet_count             10980
text                      10980
tweet_coord                 776
tweet_created             10980
tweet_location             7430
user_timezone              7403
dtype: int64

In [12]:
# imp=data.copy(,)["text","retweet_count","airline"]

In [13]:
# x=data["text"]
x=pd.concat([data["text"],data["retweet_count"],data["airline"]],axis=1)

In [14]:
del data

In [15]:
from nltk.corpus import stopwords
import string
stops = set(stopwords.words('english'))
punctuations = list(string.punctuation)
stops.update(punctuations)
stops, string.punctuation

({'!',
  '"',
  '#',
  '$',
  '%',
  '&',
  "'",
  '(',
  ')',
  '*',
  '+',
  ',',
  '-',
  '.',
  '/',
  ':',
  ';',
  '<',
  '=',
  '>',
  '?',
  '@',
  '[',
  '\\',
  ']',
  '^',
  '_',
  '`',
  'a',
  'about',
  'above',
  'after',
  'again',
  'against',
  'ain',
  'all',
  'am',
  'an',
  'and',
  'any',
  'are',
  'aren',
  "aren't",
  'as',
  'at',
  'be',
  'because',
  'been',
  'before',
  'being',
  'below',
  'between',
  'both',
  'but',
  'by',
  'can',
  'couldn',
  "couldn't",
  'd',
  'did',
  'didn',
  "didn't",
  'do',
  'does',
  'doesn',
  "doesn't",
  'doing',
  'don',
  "don't",
  'down',
  'during',
  'each',
  'few',
  'for',
  'from',
  'further',
  'had',
  'hadn',
  "hadn't",
  'has',
  'hasn',
  "hasn't",
  'have',
  'haven',
  "haven't",
  'having',
  'he',
  'her',
  'here',
  'hers',
  'herself',
  'him',
  'himself',
  'his',
  'how',
  'i',
  'if',
  'in',
  'into',
  'is',
  'isn',
  "isn't",
  'it',
  "it's",
  'its',
  'itself',
  'just',
  'll',


In [16]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [17]:
from nltk.corpus import wordnet
def get_simple_pos(tag):
    
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [18]:
from nltk import pos_tag
w = "better"
pos_tag([w])

[('better', 'RBR')]

In [19]:
def clean_review(words):
    output_words = []
    for w in words:
        if w.lower() not in stops and len(w)>0:
            pos = pos_tag([w])
            clean_word = lemmatizer.lemmatize(w, pos = get_simple_pos(pos[0][1]))
            output_words.append(clean_word.lower())
    return output_words

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [21]:
x_train_text=np.array(x_train["text"])

In [22]:
x_train_words=[x_train_text[i].split(" ") for i in range(len(x_train_text))]

In [23]:
type(x_train_words)

list

In [24]:
x_train_cleaned=[clean_review(x_train_words[i]) for i in range(len(x_train_words))]

In [25]:
x_train_combined=[" ".join(d) for d in x_train_cleaned]

In [26]:
x_train_combined

['@usairways thank you!!!',
 '@americanair kax premium. hoping flight well food, tv know work service. tnx',
 '@usairways crazy. spoken human yet. well way. http://t.co/meoalcipdd',
 '@usairways grt flight phx last week, tonight terrible. 2.5 hour tax give u water cracker compensate.',
 '@usairways thanks gate agent state college, pa able get earlier flight figure earlier connection!',
 '@americanair submit case aa customer relation two week ago, word ever since! whats point even cr?',
 '@americanair worries, love fly guys. thanks!',
 '@united z code airfare refundable?',
 "@southwestair want file formal complaint disgruntle employee laguardia ruin mltple people's travel plan yesterday",
 '@united @annricord both!',
 '@united #unitedairlines feedback benefit, correct atrocious customer service? good know',
 '@virginamerica let 2 scan passenger leave plane told someone remove bag 1st class bin? #uncomfortable',
 '@united would make day could take flight airline without hiccup end. train

In [27]:
count_vec=CountVectorizer()
x_train_features = count_vec.fit_transform(x_train_combined)

In [28]:
x_test_text=np.array(x_test["text"])

In [29]:
x_test_words=[x_test_text[i].split(" ") for i in range(len(x_test_text))]

In [30]:
type(x_test_words)

list

In [31]:
x_test_cleaned=[clean_review(x_test_words[i]) for i in range(len(x_test_words))]

In [32]:
x_test_combined=[" ".join(d) for d in x_test_cleaned]

In [33]:
x_test_combined

['@jetblue jfk airport right',
 '@americanair aa1344 cancelled flighted 2.23 rebooked u air 623/544 2.24. nonstop 2.24 u (2)?',
 '@usairways tsa precheck show boarding pas flight tomorrow...help!? #usairways #tsaprecheck',
 '@southwestair ok...i forgive guys.',
 '@americanair kudos ticket agent #2224 make passenger check bag big fit overhead.',
 "@southwestair desparately need yall make nonstop bna-&gt; tul! cmon it'll popular. 😄 (right, @annebevi @paulbev1 @mikeabramson??)",
 '@southwestair move 210pm flight #4649. main concern luggage arrive them. told sw',
 '@united @dmb41shows need plane get buffalo leave tonight. progress?',
 '@united will. thanks.',
 '@southwestair flight cancelled flighted delayed expect full compensation park ticket, hotel &amp; flight..',
 '@united horrific flight experience, guy make never want fly airplane every again!!!!!!!',
 "@usairways flight 1898 land 2 hour ago still gotten gate.. what's hold uppp 😭😭 #imtired #wannagohome",
 '@united luggages? group 20

In [34]:
x_test_features = count_vec.transform(x_test_combined)

In [35]:
# import imblearn
# undersample = imblearn.over_sampling.RandomOverSampler(sampling_strategy="not majority")
# x_train_features=undersample.fit_resample(x_train_features,y_train)

In [36]:
from sklearn.svm import SVC

In [37]:
svc=SVC()

In [38]:
svc.fit(x_train_features,y_train)

SVC()

In [39]:
svc.score(x_test_features,y_test)

0.7723132969034608

In [40]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(max_leaf_nodes=None)

In [41]:
rfc.fit(x_train_features,y_train)

RandomForestClassifier()

In [42]:

rfc.score(x_test_features,y_test)

0.7515482695810565

In [43]:
from sklearn.metrics import classification_report,confusion_matrix


In [44]:
print(classification_report(y_test,rfc.predict(x_test_features)))

              precision    recall  f1-score   support

    negative       0.80      0.89      0.84      1719
     neutral       0.59      0.45      0.51       581
    positive       0.70      0.60      0.65       445

    accuracy                           0.75      2745
   macro avg       0.70      0.65      0.67      2745
weighted avg       0.74      0.75      0.74      2745



In [45]:
Counter(y_train)

Counter({'positive': 1357, 'neutral': 1746, 'negative': 5132})

In [46]:
import imblearn
oversample = imblearn.over_sampling.RandomOverSampler(sampling_strategy="not majority",)
x_train_features,y_train=oversample.fit_resample(x_train_features,y_train)

In [47]:
x_train_features.shape

(15396, 10274)

In [48]:
# clf=SVC()
# grid={"gamma":[.01,.1,1,10,100],"C":[.01,.1,1,10,100]}
# gscv=GridSearchCV(clf,grid)
# gscv.fit(x_train,y_train)
# gscv.best_estimator_

In [49]:
# gscv.best_estimator_

In [50]:
svc=SVC()

In [51]:
svc.fit(x_train_features,y_train)

SVC()

In [52]:
svc.score(x_test_features,y_test)

0.765391621129326

In [53]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(max_leaf_nodes=None)

In [54]:
clf=RandomForestClassifier()
# for i in range(100,200,10):
grid={"max_leaf_nodes":list(np.arange(205,210))}
gscv=GridSearchCV(clf,grid)
gscv.fit(x_train_features,y_train)
print(gscv.best_estimator_)

RandomForestClassifier(max_leaf_nodes=205)


In [55]:
gscv.cv_results_

{'mean_fit_time': array([3.86349711, 3.94480219, 3.89576187, 3.89687653, 3.92947516]),
 'std_fit_time': array([0.05829653, 0.10982005, 0.09015715, 0.12038842, 0.13036652]),
 'mean_score_time': array([0.05701008, 0.05785651, 0.05581145, 0.05661106, 0.05641122]),
 'std_score_time': array([0.00116203, 0.00055495, 0.00178691, 0.0009766 , 0.00079701]),
 'param_max_leaf_nodes': masked_array(data=[205, 206, 207, 208, 209],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_leaf_nodes': 205},
  {'max_leaf_nodes': 206},
  {'max_leaf_nodes': 207},
  {'max_leaf_nodes': 208},
  {'max_leaf_nodes': 209}],
 'split0_test_score': array([0.77727273, 0.76655844, 0.76753247, 0.76623377, 0.76623377]),
 'split1_test_score': array([0.76940565, 0.76810653, 0.77005521, 0.76713219, 0.77037999]),
 'split2_test_score': array([0.79084118, 0.78856772, 0.77752517, 0.77752517, 0.78304644]),
 'split3_test_score': array([0.77297824, 0.77914907, 

In [56]:
#108,118,138--rfc


In [57]:
gscv.best_score_

0.7745516549056659

In [58]:
gscv.cv_results_

{'mean_fit_time': array([3.86349711, 3.94480219, 3.89576187, 3.89687653, 3.92947516]),
 'std_fit_time': array([0.05829653, 0.10982005, 0.09015715, 0.12038842, 0.13036652]),
 'mean_score_time': array([0.05701008, 0.05785651, 0.05581145, 0.05661106, 0.05641122]),
 'std_score_time': array([0.00116203, 0.00055495, 0.00178691, 0.0009766 , 0.00079701]),
 'param_max_leaf_nodes': masked_array(data=[205, 206, 207, 208, 209],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_leaf_nodes': 205},
  {'max_leaf_nodes': 206},
  {'max_leaf_nodes': 207},
  {'max_leaf_nodes': 208},
  {'max_leaf_nodes': 209}],
 'split0_test_score': array([0.77727273, 0.76655844, 0.76753247, 0.76623377, 0.76623377]),
 'split1_test_score': array([0.76940565, 0.76810653, 0.77005521, 0.76713219, 0.77037999]),
 'split2_test_score': array([0.79084118, 0.78856772, 0.77752517, 0.77752517, 0.78304644]),
 'split3_test_score': array([0.77297824, 0.77914907, 

In [59]:
rfc.fit(x_train_features,y_train)

RandomForestClassifier()

In [60]:

rfc.score(x_test_features,y_test)

0.7482695810564663

In [61]:
from sklearn.metrics import classification_report,confusion_matrix


In [62]:
print(classification_report(y_test,rfc.predict(x_test_features)))

              precision    recall  f1-score   support

    negative       0.84      0.83      0.84      1719
     neutral       0.55      0.57      0.56       581
    positive       0.65      0.66      0.65       445

    accuracy                           0.75      2745
   macro avg       0.68      0.69      0.68      2745
weighted avg       0.75      0.75      0.75      2745



In [63]:
print(rfc.score(x_test_features,y_test))

0.7482695810564663


## Logistic Regression

In [64]:
from sklearn.linear_model import LogisticRegression
import time
lr=LogisticRegression()
start=time.time()
lr.fit(x_train_features,y_train)
print("Time taken = ",time.time()-start)
y_pred=lr.predict(x_test_features)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

Time taken =  0.7135109901428223
              precision    recall  f1-score   support

    negative       0.88      0.80      0.84      1719
     neutral       0.54      0.63      0.58       581
    positive       0.67      0.74      0.70       445

    accuracy                           0.76      2745
   macro avg       0.70      0.72      0.71      2745
weighted avg       0.77      0.76      0.76      2745

[[1382  250   87]
 [ 140  368   73]
 [  57   60  328]]


c:\Users\Dell\anaconda3\lib\site-packages\daal4py\sklearn\linear_model\logistic_path.py:459: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [65]:
print(lr.score(x_train_features,y_train),lr.score(x_test_features,y_test))

0.9664198493115095 0.7570127504553734


## Naive Bayes

In [66]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
start=time.time()
gnb.fit(x_train_features.todense(),y_train)
print("Time taken = ",time.time()-start)
y_pred=gnb.predict(x_test_features.todense())
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


c:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


Time taken =  2.1648433208465576


c:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


              precision    recall  f1-score   support

    negative       0.81      0.54      0.65      1719
     neutral       0.33      0.33      0.33       581
    positive       0.28      0.64      0.39       445

    accuracy                           0.51      2745
   macro avg       0.47      0.51      0.46      2745
weighted avg       0.62      0.51      0.54      2745

[[928 316 475]
 [131 193 257]
 [ 90  68 287]]


In [67]:
print(gnb.score(x_train_features.todense(),y_train),gnb.score(x_test_features.todense(),y_test))

c:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
c:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


0.8390491036632892 0.5129326047358834


# Multinomial Naive Bayes


In [68]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
start=time.time()
mnb.fit(x_train_features.todense(),y_train)
print("Time taken = ",time.time()-start)
y_pred=mnb.predict(x_test_features.todense())
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


c:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


Time taken =  4.222351551055908
              precision    recall  f1-score   support

    negative       0.85      0.85      0.85      1719
     neutral       0.57      0.50      0.53       581
    positive       0.59      0.72      0.65       445

    accuracy                           0.75      2745
   macro avg       0.67      0.69      0.68      2745
weighted avg       0.75      0.75      0.75      2745

[[1453  161  105]
 [ 177  291  113]
 [  70   56  319]]


c:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


In [69]:
print(mnb.score(x_train_features.todense(),y_train),mnb.score(x_test_features.todense(),y_test))

c:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


0.8849701221096389 0.7515482695810565


c:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
